name: pr-approval

# Protection rules for PR approval
protection_rules:
  # Required reviewers before proceeding
  required_reviewers:
    - tanishq-sa
  
  # Wait time before proceeding (in minutes)
  wait_timer: 2
  
  # Deployment branch policy
  deployment_branch_policy:
    protected_branches: false
    custom_branch_policies: true
  
  # Required status checks that must pass
  required_status_checks:
    strict: true
    contexts:
      - "Deploy to Vercel / test (16.x)"
      - "Deploy to Vercel / test (18.x)"
      - "Deploy to Vercel / test (20.x)"
      - "Status Check / status"
      - "Test and Quality Check / quality-check"

# Environment variables for PR approval
environment_variables:
  APPROVAL_STAGE: "pr-approval"
  REQUIRES_MANUAL_APPROVAL: "true"

# Deployment settings
deployment_settings:
  # Auto-approve disabled
  auto_approve: false
  
  # Deployment timeout (in minutes)
  timeout_minutes: 15
  
  # Notifications
  notifications:
    on_approval_required: true
    on_approval_granted: true
    on_deployment_start: true
    on_deployment_success: true
    on_deployment_failure: true
