name: production

# Protection rules for the production environment
protection_rules:
  # Required reviewers before deployment
  required_reviewers:
    - tanishq-sa
  
  # Wait time before deployment (in minutes)
  wait_timer: 5
  
  # Deployment branch policy
  deployment_branch_policy:
    protected_branches: true
    custom_branch_policies: false
  
  # Required status checks
  required_status_checks:
    strict: true
    contexts:
      - "Deploy to Vercel / test (16.x)"
      - "Deploy to Vercel / test (18.x)"
      - "Deploy to Vercel / test (20.x)"
      - "Status Check / status"
      - "Test and Quality Check / quality-check"

# Environment variables for production
environment_variables:
  NODE_ENV: "production"
  DEPLOYMENT_ENV: "production"
  PRODUCTION_FLAG: "true"
  LOG_LEVEL: "info"

# Deployment settings
deployment_settings:
  # Auto-deploy disabled (manual approval required)
  auto_deploy: false
  
  # Deployment timeout (in minutes)
  timeout_minutes: 30
  
  # Rollback on failure
  rollback_on_failure: true
  
  # Health checks
  health_check:
    enabled: true
    timeout: 300
    retries: 3
  
  # Notifications
  notifications:
    on_success: true
    on_failure: true
    on_cancellation: true
    on_approval_required: true
    on_approval_granted: true
  
  # Security settings
  security:
    require_2fa: true
    require_code_review: true
    block_force_push: true
    block_deletion: true
